stages:
  - deploy

deploy:
  image: node:22
  stage: deploy
  only:
    - main
  before_script:
    - apt update && apt install -y openssh-client
    - echo "$SERVER_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - npm install
    - npm run build
    - scp -r dist/* $SERVER_USER@$SERVER_IP:$DESTINATION_PATH
